version: '3'

services:
  api:
    stdin_open: true
    build:
      context: .
      dockerfile: "./Dockerfile.api"
    tty: true
    ports:
      - 5000:5000
    volumes:
      - ".:/app"
      - "~/.bash_history:/root/.bash_history"
      - "~/.bash_aliases:/root/.bash_aliases"
      - "~/.bashrc:/root/.bashrc"

    command:
      ["pipenv", "run", "python", "-m", "flask", "run", "--host=0.0.0.0"]
    entrypoint:
      []
    environment:
      FLASK_ENV: development

  cli:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: "./Dockerfile"
    volumes:
      - ".:/app"
      - "~/.bash_history:/root/.bash_history"
      - "~/.bash_aliases:/root/.bash_aliases"
      - "~/.bashrc:/root/.bashrc"

  lint:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: "./Dockerfile.test"
    volumes:
      - ".:/app"

    command:
      ["pipenv", "run", "lint"]

  unit-tests:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: "./Dockerfile.test"
    volumes:
      - ".:/app"

    command:
      ["pipenv", "run", "unit"]
